
development:
  adapter: postgresql
  database: myproject 
  host: localhost


test:
  adapter: postgresql
  database: myproject 
  host: localhost

production:
  adapter: postgresql
  database: myproject 
  host: localhost